name: KOKORO_Jarijari
version: 1.0
main: com.shamison.Jarijari
commands:
  oauth:
    description: This is a demo command.
    usage: /<command> [player]
  pin:
    description: This is a demo command.
    usage: /<command> [player]